{% set name = "OnStove" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Open-Source-Spatial-Clean-Cooking-Tool/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 5dabcac3047d03597635bd0c40f6066d27b4bd854b9e9680ed72e46e21ea752a

build: 
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - dill
    - geopandas
    - jupyterlab
    - matplotlib-base <=3.5.2
    - plotnine
    - psutil
    - psycopg2
    - pyproj <=3.3.1
    - python >=3.10
    - python-decouple
    - rasterio
    - scikit-image
    - svgpathtools
    - svgpath2mpl

test:
  imports:
    - onstove

about:
  home: https://github.com/Open-Source-Spatial-Clean-Cooking-Tool/OnStove
  summary: 'Python-based geospatial cost-benefit clean cooking tool, OnStove'
  description: |
    OnStove is a geospatial cost-benefit clean cooking tool that calculates 
    the net-benefits of different stove options in a given geography and compares 
    all stoves to one another with regards to their net-benefit.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://onstove-documentation.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/Open-Source-Spatial-Clean-Cooking-Tool/OnStove

extra:
  recipe-maintainers:
    - camiloramirezgo
    - babakkhavari
